/* R48 authored motion profiles. Pure presentation data; no balance or save values. */
'use strict';
const RF_MOTION = (() => {
 const data = {
  "gaits": [
    {
      "id": "runner",
      "family": "run",
      "stride": 62,
      "bob": 1.7,
      "sway": 0.8,
      "lean": 0.055,
      "turn": 15,
      "weight": 0.3,
      "hover": 0,
      "cloth": 0,
      "foot": "soft",
      "spawn": "dust",
      "death": "fall",
      "fx": "dust",
      "ground": 0.382
    },
    {
      "id": "heavy",
      "family": "heavy",
      "stride": 82,
      "bob": 0.95,
      "sway": 0.7,
      "lean": 0.021,
      "turn": 4,
      "weight": 1,
      "hover": 0,
      "cloth": 0.25,
      "foot": "heavy",
      "spawn": "dust",
      "death": "armor",
      "fx": "dust",
      "ground": 0.3797
    },
    {
      "id": "knight",
      "family": "march",
      "stride": 72,
      "bob": 1.0,
      "sway": 0.55,
      "lean": 0.027,
      "turn": 7,
      "weight": 0.72,
      "hover": 0,
      "cloth": 0.4,
      "foot": "metal",
      "spawn": "dust",
      "death": "armor",
      "fx": "metal",
      "ground": 0.4054
    },
    {
      "id": "shaman",
      "family": "robe",
      "stride": 65,
      "bob": 0.85,
      "sway": 1.0,
      "lean": 0.025,
      "turn": 6,
      "weight": 0.35,
      "hover": 0,
      "cloth": 0.8,
      "foot": "soft",
      "spawn": "mist",
      "death": "soul",
      "fx": "wisp",
      "ground": 0.4289
    },
    {
      "id": "ghost",
      "family": "float",
      "stride": 96,
      "bob": 2.9,
      "sway": 1.4,
      "lean": 0.025,
      "turn": 3,
      "weight": 0.1,
      "hover": 1,
      "cloth": 1,
      "foot": "none",
      "spawn": "mist",
      "death": "soul",
      "fx": "wisp",
      "ground": 0.4289
    },
    {
      "id": "berserker",
      "family": "rage",
      "stride": 74,
      "bob": 1.5,
      "sway": 1.1,
      "lean": 0.047,
      "turn": 8,
      "weight": 0.85,
      "hover": 0,
      "cloth": 0.35,
      "foot": "heavy",
      "spawn": "ash",
      "death": "ember",
      "fx": "ember",
      "ground": 0.3875
    },
    {
      "id": "shieldguard",
      "family": "guard",
      "stride": 78,
      "bob": 0.85,
      "sway": 0.45,
      "lean": 0.017,
      "turn": 5,
      "weight": 0.9,
      "hover": 0,
      "cloth": 0.55,
      "foot": "metal",
      "spawn": "dust",
      "death": "armor",
      "fx": "metal",
      "ground": 0.3304
    },
    {
      "id": "warlock",
      "family": "robe",
      "stride": 75,
      "bob": 1.0,
      "sway": 1.15,
      "lean": 0.02,
      "turn": 4,
      "weight": 0.35,
      "hover": 0.15,
      "cloth": 1,
      "foot": "none",
      "spawn": "rune",
      "death": "soul",
      "fx": "rune",
      "ground": 0.3508
    },
    {
      "id": "frostborn",
      "family": "heavy",
      "stride": 64,
      "bob": 0.85,
      "sway": 0.55,
      "lean": 0.022,
      "turn": 5,
      "weight": 0.85,
      "hover": 0,
      "cloth": 0.2,
      "foot": "ice",
      "spawn": "ice",
      "death": "ice",
      "fx": "ice",
      "ground": 0.2883
    },
    {
      "id": "necromancer",
      "family": "robe",
      "stride": 78,
      "bob": 0.6,
      "sway": 0.85,
      "lean": 0.018,
      "turn": 3,
      "weight": 0.35,
      "hover": 0,
      "cloth": 1,
      "foot": "soft",
      "spawn": "ash",
      "death": "soul",
      "fx": "soul",
      "ground": 0.3976
    },
    {
      "id": "saboteur",
      "family": "skulk",
      "stride": 50,
      "bob": 1.1,
      "sway": 0.6,
      "lean": 0.064,
      "turn": 16,
      "weight": 0.3,
      "hover": 0,
      "cloth": 0.2,
      "foot": "soft",
      "spawn": "smoke",
      "death": "smoke",
      "fx": "dust",
      "ground": 0.3015
    },
    {
      "id": "voidwalker",
      "family": "float",
      "stride": 108,
      "bob": 2.1,
      "sway": 1.3,
      "lean": 0.026,
      "turn": 3,
      "weight": 0.1,
      "hover": 1,
      "cloth": 1,
      "foot": "none",
      "spawn": "void",
      "death": "void",
      "fx": "void",
      "ground": 0.2883
    },
    {
      "id": "shardling",
      "family": "shard",
      "stride": 55,
      "bob": 1.2,
      "sway": 1.15,
      "lean": 0.042,
      "turn": 12,
      "weight": 0.4,
      "hover": 0,
      "cloth": 0.1,
      "foot": "ice",
      "spawn": "ice",
      "death": "ice",
      "fx": "ice",
      "ground": 0.3586
    },
    {
      "id": "mirrorborn",
      "family": "mirror",
      "stride": 88,
      "bob": 0.55,
      "sway": 0.65,
      "lean": 0.012,
      "turn": 8,
      "weight": 0.35,
      "hover": 0.15,
      "cloth": 0.2,
      "foot": "glass",
      "spawn": "mirror",
      "death": "mirror",
      "fx": "mirror",
      "ground": 0.3664
    },
    {
      "id": "forgekin",
      "family": "heavy",
      "stride": 86,
      "bob": 0.85,
      "sway": 0.6,
      "lean": 0.025,
      "turn": 3,
      "weight": 1,
      "hover": 0,
      "cloth": 0.55,
      "foot": "forge",
      "spawn": "ash",
      "death": "ember",
      "fx": "ember",
      "ground": 0.3508
    },
    {
      "id": "eraser",
      "family": "erase",
      "stride": 76,
      "bob": 1.1,
      "sway": 1.2,
      "lean": 0.035,
      "turn": 9,
      "weight": 0.3,
      "hover": 0.2,
      "cloth": 0.75,
      "foot": "none",
      "spawn": "void",
      "death": "void",
      "fx": "void",
      "ground": 0.3508
    },
    {
      "id": "stormherald",
      "family": "storm",
      "stride": 65,
      "bob": 1.5,
      "sway": 1.0,
      "lean": 0.029,
      "turn": 10,
      "weight": 0.25,
      "hover": 0.45,
      "cloth": 0.8,
      "foot": "none",
      "spawn": "storm",
      "death": "electric",
      "fx": "electric",
      "ground": 0.3508
    },
    {
      "id": "aberration",
      "family": "odd",
      "stride": 69,
      "bob": 1.2,
      "sway": 1.55,
      "lean": 0.037,
      "turn": 6,
      "weight": 0.6,
      "hover": 0,
      "cloth": 0.6,
      "foot": "soft",
      "spawn": "void",
      "death": "void",
      "fx": "void",
      "ground": 0.3664
    }
  ],
  "bosses": [
    {
      "id": "iron_fang",
      "family": "heavy",
      "stride": 96.36,
      "bob": 1.4,
      "sway": 0.8,
      "turn": 4,
      "weight": 1,
      "motif": "fang",
      "particle": "debris",
      "root": 64,
      "chord": [
        1,
        1.5,
        2
      ],
      "wave": "triangle",
      "noise": 650,
      "beat": 0.085,
      "world": 1,
      "atlasKey": "boss_motion_1_r48",
      "frames": 12,
      "cell": 256,
      "hover": 0,
      "lean": 0.023,
      "cloth": 0.7,
      "foot": "boss",
      "fx": "debris",
      "death": "fang",
      "spawn": "fang",
      "ground": 0.4785
    },
    {
      "id": "ice_queen",
      "family": "float",
      "stride": 120.12,
      "bob": 3.4,
      "sway": 1.1,
      "turn": 3,
      "weight": 0.2,
      "motif": "crown",
      "particle": "shard",
      "root": 294,
      "chord": [
        1,
        1.5,
        2.51
      ],
      "wave": "sine",
      "noise": 4300,
      "beat": 0.065,
      "world": 2,
      "atlasKey": "boss_motion_2_r48",
      "frames": 12,
      "cell": 256,
      "hover": 1,
      "lean": 0.023,
      "cloth": 0.7,
      "foot": "none",
      "fx": "shard",
      "death": "crown",
      "spawn": "crown",
      "ground": 0.48
    },
    {
      "id": "ash_necromancer",
      "family": "robe",
      "stride": 108.24000000000001,
      "bob": 1.8,
      "sway": 1.2,
      "turn": 3,
      "weight": 0.45,
      "motif": "souls",
      "particle": "mist",
      "root": 87,
      "chord": [
        1,
        1.19,
        2.02
      ],
      "wave": "sine",
      "noise": 1400,
      "beat": 0.14,
      "world": 3,
      "atlasKey": "boss_motion_3_r48",
      "frames": 12,
      "cell": 256,
      "hover": 0,
      "lean": 0.023,
      "cloth": 0.7,
      "foot": "none",
      "fx": "mist",
      "death": "souls",
      "spawn": "souls",
      "ground": 0.48
    },
    {
      "id": "stone_colossus",
      "family": "heavy",
      "stride": 122.10000000000001,
      "bob": 0.9,
      "sway": 0.7,
      "turn": 2,
      "weight": 1,
      "motif": "plates",
      "particle": "debris",
      "root": 39,
      "chord": [
        1,
        1.41,
        2.82
      ],
      "wave": "triangle",
      "noise": 280,
      "beat": 0.115,
      "world": 4,
      "atlasKey": "boss_motion_4_r48",
      "frames": 12,
      "cell": 256,
      "hover": 0,
      "lean": 0.023,
      "cloth": 0.7,
      "foot": "boss",
      "fx": "debris",
      "death": "plates",
      "spawn": "plates",
      "ground": 0.48
    },
    {
      "id": "crimson_dragon",
      "family": "wing",
      "stride": 108.9,
      "bob": 2.5,
      "sway": 1.3,
      "turn": 5,
      "weight": 0.85,
      "motif": "wings",
      "particle": "ember",
      "root": 58,
      "chord": [
        1,
        1.33,
        2.66
      ],
      "wave": "sawtooth",
      "noise": 1200,
      "beat": 0.12,
      "world": 5,
      "atlasKey": "boss_motion_5_r48",
      "frames": 12,
      "cell": 256,
      "hover": 0.3,
      "lean": 0.023,
      "cloth": 0.7,
      "foot": "boss",
      "fx": "ember",
      "death": "wings",
      "spawn": "wings",
      "ground": 0.48
    },
    {
      "id": "dark_king",
      "family": "march",
      "stride": 104.28,
      "bob": 1.4,
      "sway": 0.7,
      "turn": 4,
      "weight": 0.8,
      "motif": "crownblade",
      "particle": "rune",
      "root": 73,
      "chord": [
        1,
        1.5,
        2.25
      ],
      "wave": "triangle",
      "noise": 1800,
      "beat": 0.095,
      "world": 6,
      "atlasKey": "boss_motion_6_r48",
      "frames": 12,
      "cell": 256,
      "hover": 0,
      "lean": 0.023,
      "cloth": 0.7,
      "foot": "boss",
      "fx": "rune",
      "death": "crownblade",
      "spawn": "crownblade",
      "ground": 0.48
    },
    {
      "id": "rift_knight",
      "family": "shard",
      "stride": 89.76,
      "bob": 1.7,
      "sway": 1.1,
      "turn": 10,
      "weight": 0.7,
      "motif": "riftblade",
      "particle": "shard",
      "root": 138,
      "chord": [
        1,
        1.414,
        2.83
      ],
      "wave": "triangle",
      "noise": 3200,
      "beat": 0.055,
      "world": 7,
      "atlasKey": "boss_motion_7_r48",
      "frames": 12,
      "cell": 256,
      "hover": 0,
      "lean": 0.023,
      "cloth": 0.7,
      "foot": "boss",
      "fx": "shard",
      "death": "riftblade",
      "spawn": "riftblade",
      "ground": 0.3898
    },
    {
      "id": "glass_seer",
      "family": "mirror",
      "stride": 117.48,
      "bob": 2.0,
      "sway": 1.0,
      "turn": 4,
      "weight": 0.2,
      "motif": "mirrors",
      "particle": "shard",
      "root": 392,
      "chord": [
        1,
        1.33,
        1.78
      ],
      "wave": "sine",
      "noise": 4800,
      "beat": 0.085,
      "world": 8,
      "atlasKey": "boss_motion_8_r48",
      "frames": 12,
      "cell": 256,
      "hover": 1,
      "lean": 0.023,
      "cloth": 0.7,
      "foot": "none",
      "fx": "shard",
      "death": "mirrors",
      "spawn": "mirrors",
      "ground": 0.382
    },
    {
      "id": "void_smith",
      "family": "heavy",
      "stride": 124.08000000000001,
      "bob": 0.85,
      "sway": 0.65,
      "turn": 2,
      "weight": 1,
      "motif": "anvil",
      "particle": "ember",
      "root": 46,
      "chord": [
        1,
        2.76,
        4.13
      ],
      "wave": "triangle",
      "noise": 780,
      "beat": 0.14,
      "world": 9,
      "atlasKey": "boss_motion_9_r48",
      "frames": 12,
      "cell": 256,
      "hover": 0,
      "lean": 0.023,
      "cloth": 0.7,
      "foot": "boss",
      "fx": "ember",
      "death": "anvil",
      "spawn": "anvil",
      "ground": 0.3898
    },
    {
      "id": "name_collector",
      "family": "robe",
      "stride": 119.46000000000001,
      "bob": 1.5,
      "sway": 1.2,
      "turn": 3,
      "weight": 0.25,
      "motif": "pages",
      "particle": "paper",
      "root": 112,
      "chord": [
        1,
        1.06,
        1.498
      ],
      "wave": "sine",
      "noise": 2300,
      "beat": 0.16,
      "world": 10,
      "atlasKey": "boss_motion_10_r48",
      "frames": 12,
      "cell": 256,
      "hover": 0,
      "lean": 0.023,
      "cloth": 0.7,
      "foot": "none",
      "fx": "paper",
      "death": "pages",
      "spawn": "pages",
      "ground": 0.3976
    },
    {
      "id": "sky_devourer",
      "family": "wing",
      "stride": 113.52000000000001,
      "bob": 3.7,
      "sway": 1.5,
      "turn": 4,
      "weight": 0.65,
      "motif": "stormwings",
      "particle": "spark",
      "root": 104,
      "chord": [
        1,
        1.9,
        3.8
      ],
      "wave": "triangle",
      "noise": 5200,
      "beat": 0.06,
      "world": 11,
      "atlasKey": "boss_motion_11_r48",
      "frames": 12,
      "cell": 256,
      "hover": 0.3,
      "lean": 0.023,
      "cloth": 0.7,
      "foot": "boss",
      "fx": "spark",
      "death": "stormwings",
      "spawn": "stormwings",
      "ground": 0.3781
    },
    {
      "id": "void_archon",
      "family": "float",
      "stride": 125.4,
      "bob": 2.8,
      "sway": 1.2,
      "turn": 3,
      "weight": 0.3,
      "motif": "singularity",
      "particle": "shard",
      "root": 51,
      "chord": [
        1,
        1.059,
        2.118
      ],
      "wave": "sine",
      "noise": 950,
      "beat": 0.17,
      "world": 12,
      "atlasKey": "boss_motion_12_r48",
      "frames": 12,
      "cell": 256,
      "hover": 1,
      "lean": 0.023,
      "cloth": 0.7,
      "foot": "none",
      "fx": "shard",
      "death": "singularity",
      "spawn": "singularity",
      "ground": 0.3937
    }
  ],
  "assets": {
    "boss_motion_1_r48": "images/boss_motion_1_r48.webp",
    "boss_motion_2_r48": "images/boss_motion_2_r48.webp",
    "boss_motion_3_r48": "images/boss_motion_3_r48.webp",
    "boss_motion_4_r48": "images/boss_motion_4_r48.webp",
    "boss_motion_5_r48": "images/boss_motion_5_r48.webp",
    "boss_motion_6_r48": "images/boss_motion_6_r48.webp",
    "boss_motion_7_r48": "images/boss_motion_7_r48.webp",
    "boss_motion_8_r48": "images/boss_motion_8_r48.webp",
    "boss_motion_9_r48": "images/boss_motion_9_r48.webp",
    "boss_motion_10_r48": "images/boss_motion_10_r48.webp",
    "boss_motion_11_r48": "images/boss_motion_11_r48.webp",
    "boss_motion_12_r48": "images/boss_motion_12_r48.webp"
  },
  "environments": [
    "grove",
    "ice",
    "cinders",
    "marsh",
    "peaks",
    "citadel",
    "shards",
    "mirrors",
    "forge",
    "archive",
    "sky",
    "void"
  ]
};
 for (const list of [data.gaits,data.bosses]) { for(const p of list) Object.freeze(p); Object.freeze(list); }
 Object.freeze(data.assets); Object.freeze(data.environments); return Object.freeze(data);
})();
